services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
